### ISSUE TITLE
How to produce a large amount of RST tree using this tool?

### ISSUE THREAD

**Issue by lezhang7** [arne-cl/rst-workbench#13]
I'm trying to using RST tree for NLP research, so i need to utilize this tool to transfer my corpus into RST tree, but how could i use it to generate a large amount of RST tree instead just one?

**Comment by arne-cl** [comment]
Dear @Magiccircuit,

please have a look at the example script `rst_workbench.py`.
In general, all the parsers used in the rst-workbench have a REST endpoint `/parse`
to which you can `POST` your input file. They all work the same way as [stagedp-service](https://github.com/NLPbox/stagedp-service), which I assume you are already using.

Let me know if this works for you.
Please don't forget to cite rst-workbench in addition to the individual parsers,
if it helps you with your research.
